### ISSUE TITLE
Test with Omeka S v1.3.0

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/neatline-spa#121]

**Comment by jamiefolsom** [comment]
@akstuhl I believe this can be closed, correct? If there are any quirks to using Neatline with Omeka S v1.3.0, please just document those in the readme for the SPA or the module. Thanks!

**Comment by akstuhl** [comment]
@jamiefolsom Correct! The update to 1.3.0 runs smoothly and doesn't interfere with any Neatline functionality.

**Comment by jamiefolsom** [comment]
Great, thanks.
