### ISSUE TITLE
Icons not included in build version of spa

### ISSUE THREAD

**Issue by ZoeLeBlanc** [performant-software/neatline-spa#122]
## Expected Behavior
When you build the neatline spa and serve it from omeka, it should look identical to hosting it from node.

## Current Behavior
Currently when built, the icons from semantic ui react aren't included in the build. I think this has to do with how we are specifying the files to host from the server. Do we need to explicitly state that it should also host the media files?

### Failure Logs
  Please provide any relevant log snippets or files.

### Steps to Reproduce
Pull down from my branch and try running the app both from build and served versions

### Background Information
  Please include context of your setup, such as your operating system and other relevant features.

**Comment by akstuhl** [comment]
I ran into this issue when testing the built app inside the Omeka view container, and added a crude workaround in https://github.com/scholarslab/neatline-omeka-s/pull/57, but that only addresses the rendered-inside-Omeka case. There should be a more universal solution to the problem, which seems similar to the one described here: https://stackoverflow.com/questions/43963594/react-semantic-uis-icones-are-not-loading-with-webpack-middle-ware

**Comment by eam5** [comment]
Resolved in 7b07ff21befad19cc9cffa144562d660f24acd6c
