### ISSUE TITLE
Filtering records creates infinite loop

### ISSUE THREAD

**Issue by ZoeLeBlanc** [performant-software/neatline-spa#123]
## Expected Behavior
I'm trying to filter records initially on search but eventually through the timeline. I tried implementing a filter in a redux saga and somehow created an infinite loop that crashes the app. I realize that according to the redux docs filtering state should be done with a selector https://redux.js.org/recipes/computing-derived-data so let me know if I should just do that instead, but I would like to be able to put the filter into state to update multiple components so I think getting redux working is ideal.

## Current Behavior
Infinite loop when action dispatched that crashes the app, requiring a forced quit out of the browser 😭 

### Steps to Reproduce

If you go to my branch zgl/editor-tweaks, click on or create an exhibit, then under the exhibit, click on the records button in the menu on the far right. You should then be on the exhibit show records view. In the table, there's a search bar. Input your search term (has to be the title of the record) and then press enter. You should then enter an infinite loop. 

The code is initiated from the records index.js, and then I created an action type, a saga, and a reducer under exhibitShow.

**Comment by jamiefolsom** [comment]
Hi @ZoeLeBlanc -- duly noted -- I believe @akstuhl can help you with this tomorrow. Thanks!

**Comment by ZoeLeBlanc** [comment]
Thanks to @akstuhl this bug was fixed in the latest commit 🎉 . Turns out you need to not use the same variable names when setting and getting state 😬
