### ISSUE TITLE
Record selection/updating bugs

### ISSUE THREAD

**Issue by akstuhl** [performant-software/neatline-spa#126]
## Expected Behavior
Creating and saving a new record within an exhibit will persist that record to the server and update the UI to indicate that the user is now editing an existing record. Once saved, the user will be able to add geometry features to the record using the draw tools.

## Current Behavior
Upon saving a new record, the record editor UI still reflects the "new record" header in the form's breadcrumbs header. Returning to the records list after saving fires an error, and in some cases afterward the map will only appear in the Exhibit Settings view, not in the Records view, until the page is reloaded. These impacts on UI state are compounded when adding geometry features to a new or existing record, which in some cases likewise causes the map to disappear and requires a reload. In some cases, also, a new record with '???' shown as the title is persisted to the server.

### Steps to Reproduce
Once inside the editor view for a Neatline exhibit in the standalone SPA, create a new record, save it,  add geometry features, then attempt to return to the records list and Exhibit view.

### Background Information
Running Omeka S with Neatline module via MAMP on Mac OS X, with Neatline SPA running via yarn.

**Comment by akstuhl** [comment]
Likely related: when a record is selected, clicking on the map to deselect (expected behavior) likewise causes the Records view to disappear, including the map.

**Comment by akstuhl** [comment]
WIP notes:
- a main problem was that the reducer for update response handling would set the returned record as editorRecord; since all records get updated every time the cache is synced (why?), this would change the editor record to the last record and mess up various deselect-select cycles
- remaining problems:
  - if you create a new record and save it successfully, you stay in the new record view (it should switch you over to editing that record, via the URL)
  - if you draw geometry while the record form is still labeled New Record, it will disappear from the map after trying to save. I THINK this same input causes a new record to appear in the list labeled '???' and persist to the server. resolving the above item may resolve this.
  - record selection via URL doesn't work - end of URL is stripped out and exhibit is loaded normally

**Comment by jamiefolsom** [comment]
@akstuhl Great, thanks for this update.
