### ISSUE TITLE
Test on record display is truncated in public view

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/neatline-spa#139]
<img width="415" alt="Screenshot 2019-05-31 15 12 01" src="https://user-images.githubusercontent.com/882377/58729107-80d15600-83b6-11e9-9136-e9fca9cfb9b7.png">

**Comment by jeremyboggs** [comment]
Unless this is an issue for a specific browser that's not mentioned here, I cannot replicate this issue.

**Comment by eam5** [comment]
Resolved in 7b07ff21befad19cc9cffa144562d660f24acd6c
