### ISSUE TITLE
Record editor form/functionality appearing for non-admins

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/neatline-spa#22]
From Andy: "It shouldn’t display the editor forms / functionality at all if you’re not logged in as an admin, so that’s a bug."

**Comment by feralresearch** [comment]
Request: Please add permission claims to JWT token

**Comment by akstuhl** [comment]
See https://github.com/performant-software/neatline-omeka-s/issues/34 for notes on decisions to be resolved w.r.t. passing permissions information.

**Comment by jamiefolsom** [comment]
@tezcatlipoca assigning to Summer 2, since we need to resolve the questions raised in https://github.com/performant-software/neatline-omeka-s/issues/34

**Comment by akstuhl** [comment]
This appears to be resolved by the editor UI update in #124.
