### ISSUE TITLE
Front-end refactor

### ISSUE THREAD

**Issue by akstuhl** [performant-software/neatline-spa#37]
As a Neatline developer, I want the codebase to be structured in a consistent and legible way, following conventions familiar to React/Redux developers where appropriate. The start of the Summer 2018 development sprint is a good moment to bring in input from more team members in designing and revising toward this structure.

**Comment by jamiefolsom** [comment]
@akstuhl @tezcatlipoca is this closed or superceded by #49 and/or #36 ?

**Comment by akstuhl** [comment]
@jamiefolsom @tezcatlipoca Both issues in this epic have been closed by PR merges; my understanding is that the refactoring approach has been decided on, implemented for a subset of the codebase, and currently being implemented for the rest. So maybe this epic makes sense to keep open / assign as appropriate for that remaining completion.

**Comment by jamiefolsom** [comment]
Thanks, @akstuhl -- @tezcatlipoca would you create issues for specifically what remains to be done to complete the refactor?

**Comment by jamiefolsom** [comment]
@tezcatlipoca I believe you've either completed this, or will tomorrow. When you've deployed the refactor to staging, please go ahead and close. Thx!

**Comment by jamiefolsom** [comment]
Closing as complete. @tezcatlipoca if there are remaining refactor tasks, would you open new issues?
