### ISSUE TITLE
Add locale strings for other languages

### ISSUE THREAD

**Issue by akstuhl** [performant-software/neatline-spa#41]
As a Neatline developer, following the determination of an approach for internationalization (#38), I want the application to feature locale strings for multiple languages as a basis for testing their display and a model for further contribution.

**Comment by jamiefolsom** [comment]
Infrastructure is now in place. To complete this task, we will periodically need to:

1. set up a file for a new language, 
2. make that file available to a translator,
3. translate the strings
4. import, build and release
5. announce language support

See: #84

**Comment by jamiefolsom** [comment]
Done for existing strings, and for en and es. Closing in favor of #84.
