### ISSUE TITLE
Support exhibit-level WMS layers

### ISSUE THREAD

**Issue by akstuhl** [performant-software/neatline-spa#52]
As a Neatline user, I want to be able to set WMS fields in my exhibit settings to have that WMS tile source appear among the base layers for my exhibit map. If I have set a WMS source, have not set an image URL for the exhibit, and have selected "None (image or WMS)" for the default spatial layer, the WMS source should be used as the default base layer for my exhibit.

**Comment by feralresearch** [comment]
Closed by #55
