### ISSUE TITLE
Preview update on creation before save

### ISSUE THREAD

**Issue by feralresearch** [performant-software/neatline-spa#57]
When geometry is created on a record before it is saved, the live-preview of things like color and stroke width don't apply. This has to do with the way the map is drawn, as the new geometries aren't present in the current render loop.

**Comment by jamiefolsom** [comment]
@tezcatlipoca can you update this ticket, either closing as complete or moving to Summer 2?

**Comment by feralresearch** [comment]
I am handling this MVP style, by disabling property editing (Style tab) until after initial save. If this is not expected behavior, let's re-open the ticket (or a new one) with a new user story.
