### ISSUE TITLE
zoom/focus record fields to map behavior,

### ISSUE THREAD

**Issue by feralresearch** [performant-software/neatline-spa#58]
Ensure the zoom/focus record fields to map behavior

**Comment by akstuhl** [comment]
Possible duplicate of #30 - @tezcatlipoca, does that seem right?

**Comment by jamiefolsom** [comment]
As discussed just now, @tezcatlipoca, let's tackle this and #56 in a single PR, rather than as part of a larger catch-all PR.

**Comment by feralresearch** [comment]
Duplicate of #30

**Comment by feralresearch** [comment]
This is a potentially expensive operation, probably should not do on every zoom transition
