### ISSUE TITLE
Convert normalized text fields (such as opacity) to 0-1 sliders

### ISSUE THREAD

**Issue by feralresearch** [performant-software/neatline-spa#64]
Currently fields are enforced 0-1, should change to be sliders instead. 

Not committed yet, but considering using 
https://www.npmjs.com/package/react-rangeslider

**Comment by feralresearch** [comment]
Closed by #85

**Comment by jamiefolsom** [comment]
@tezcatlipoca would you add steps for @SteveMarvin to test?

**Comment by feralresearch** [comment]
https://neatline-3-staging.herokuapp.com/s/Test/neatline

Log in

Add or edit a record  - on the STYLE tab, verify that the following sliders adjust the expected property and that you can save and reload the values:

Fill Opacity, Stroke Opacity, Selected - Stroke Opacity, Selected - Fill Opacity, Stroke Width

**Comment by SteveMarvin** [comment]
Working! Sliders work and save.

**Comment by jamiefolsom** [comment]
closed by #85
