### ISSUE TITLE
Clear all geometry button in record editor

### ISSUE THREAD

**Issue by akstuhl** [performant-software/neatline-spa#75]
As a Neatline user, I want to be able to clear all geometry features associated with a particular record while editing it, following 2.6.1 functionality.
- Implementation-wise, the button should set the record's coverage field to an empty feature set.
- UX-wise, it might be good to have a confirmation dialog.

**Comment by feralresearch** [comment]
To Test:

Create or edit a record. 

Click the "clear" button

Verify all the geometry is removed from the map
