### ISSUE TITLE
As an exhibit editor, I want to enter dates into records easily and without errors

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/neatline-spa#76]
Have a look at http://react-day-picker.js.org/

**Comment by feralresearch** [comment]
closed by #85

**Comment by jamiefolsom** [comment]
@tezcatlipoca would you add steps for @SteveMarvin to test?

**Comment by feralresearch** [comment]
Login and go to:
https://neatline-3-staging.herokuapp.com/s/Test/neatline

1. Create or edit an existing style record. Click on a field that contains a date

2. Verify that the datepicker appears

3. Verify you can save a date and return to see that value. After returning, clicking on the date field should pull up the datepicker pointed to that date. 

There are four dates: start/end/after/before

**Comment by SteveMarvin** [comment]
Working!

**Comment by jamiefolsom** [comment]
Closed by #85
